services:
  - type: web
    name: voting-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: voting-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: voting-db
    databaseName: voting
    user: voting_user
    plan: free
